### ISSUE TITLE
December 2024 - community meeting tracking thread

### ISSUE THREAD

**Issue by ekzhang** [ekzhang/setwithfriends#162]
Preparing for the first community meeting. Let's get Set with Friends development back up and running smoothly!

### Goals

Development flow

- [x] Get site development back up and update dependencies #161
- [x] Make sure deployment pipeline is still functioning (edit: it's not) 
   <img width="1192" alt="image" src="https://github.com/user-attachments/assets/d8298f78-afd4-4866-b906-8b3b10d741a5" />
- [x] Fix FIREBASE_TOKEN in deployment pipeline by regenerating `firebase login:ci`, removing the 4 years old token
- [x] Fix `firebase deploy -P staging --only functions` not working due to weird typescript issues #164
- [x] Switch from CRA to Vite #165
- [x] Sort imports 0381ef40faeb6d8553813023abe3da9f26f82735

Bug fixes

- [x] Investigate "game not ending" issue (possibly related to #160, reported separately in Discord) #171
- [x] Fix profile of user not loading if game data was cleared c2bf172c0c8baa4bcbcd927f13c290738c936601
- [x] Investigate race condition on Firefox (#159)

Backend (Note: existing scripts are not working right now, they're too slow since the site now has a lot of games / users)

- [x] Add script to add/remove admin access #170
- [x] Restrict database rules to prevent spam bot access #163
- [x] Import existing games back into database but in a cheaper store (GCS or Firestore) to retain data without the exorbitant price.

### Note

> - Solution is to use GCS ($0.02/GB) or Cloud Firestore ($0.156/GB) for historical games. I can move stuff over gradually, over time.
> - Cloud Firestore would be a bit pricier, but honestly not that much. 30 GB would be like $5/month, which is perfectly reasonable. It's not like the absurd $5/GB price that Realtime Database has been charging me for the past few years.

**Comment by ekzhang** [comment]
Going to cut a release, v3.3.0, after the development / deployment flow fixes and the profile loading.

**Comment by ekzhang** [comment]
Alright, cutting a release now at the airport.

**Comment by ekzhang** [comment]
**Design notes for cost reduction / retaining historical games:**

Basically, we need to store old game data somewhere other than Firebase Realtime Database (RTDB). The advantage of RTDB is that it's simple and fast, and all data is stored there right now.

We have two main options, Cloud Firestore (Firestore) and Google Cloud Storage (GCS). Firestore is more of a general-purpose database, and it costs $0.156/GB and is relatively cheaper per operation, so it would be possible to build most of Set with Friends on Firestore if we were going from scratch. GCS is just a standard object store like S3.

Moving historical game data to Firestore might make sense, or if we wanted to transfer _all_ game data to Firestore and just never place it in RTDB. However, I think this might make our data get fragmented, and this seems not super worth it since the document model of Firestore is a little different from RTDB. Probably not worth the complexity unless we plan to eventually migrate completely to Firestore, which I don't see a compelling argument for.

In that case, storing in GCS seems like the best option. I think the easiest way to do this while avoiding too much game logic reimplementation is to do some kind of _storage tiering_, where I have a daily job that archives game data into GCS after one day and clears them from RTDB. Then I can write a cloud function to repopulate the game data just-in-time if it's being viewed by someone via link.

Anyway, I expect this to reduce the cost of storing game data to about $0.50/month/1M games, which is a lot cheaper than the $15/month/1M games I was paying before & more sustainable. Other metadata will stay in RTDB indefinitely (cost ~$2/month/1M games), but if it becomes an issue, we can extend storage tiering to that as well.

I plan to implement this today.

**Comment by ekzhang** [comment]
Alright, this took quite a few hours of work. But v3.4.0 is released now, and I'm running a big ad hoc ETL job in Python to move the database backup into individually compressed S3 files! Closing since we're done.
